baseURL = "https://dasapex.github.io/course=atlas/"
locale = 'en-ph'
title = 'Course Atlas'

disableKinds = ["taxonomy", "term", "RSS"]

[params]
description = "Interactive FEU Tech BS Civil Engineering curriculum map"
author = "Alejandrino III Abrina"

[build]
writeStats = true

[minify]
minifyOutput = true

[security]
  allowContent = ['.*']
